<digit> ::= [0-9]
<number> ::= <digit>+

<alpha> ::= [a-zA-Z]
<word> ::= <alpha>+

<create-sql> ::= "create"
<insert-sql> ::= "insert"
<drop-sql> ::= "drop"
<select-sql> ::= "select"
<update-sql> ::= "update"
